### ISSUE TITLE
German Language file

### ISSUE THREAD

**Issue by demlak** [FriendsOfFlarum/user-directory#35]
Hi,
since i'm not into github, i try to help here instead of pull request thingy..

german language file: de.yml
```
fof-user-directory:
    forum:
        search:
            users_heading: 'Suche in allen Benutzern nach "{query}"'
        page:
            nav: Benutzerliste
            sort:
                relevance: Relevanz
                default: Standard
                username_az: Benutzername (a-z)
                username_za: Benutzername (z-a)
                newest: Neuester
                oldest: Ältester
                seen_recent: Kürzlich online
                seen_oldest: Längstens abwesend
                most_posts: Meiste Beiträge
                least_posts: Wenigste Beiträge
                most_discussions: Meiste Themen
                least_discussions: Wenigste Themen
    admin:
        permissions:
            view_user_directory: Einsicht Benutzerliste
        settings:
            title: Einstellungen Benutzerliste
            link: Füge Link zur Homepage für berechtigte Benutzer hinzu
```
